package com.persistence.dynamo.item;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.model.enums.CreditCard;
import com.model.enums.TransactionStatus;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

@DynamoDBTable(tableName = "transaction")
public class TransactionItem {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String uid;

    @DynamoDBRangeKey(attributeName = "sid")
    private Long sid;

    @DynamoDBAttribute(attributeName = "clientName")
    private String clientName;

    @DynamoDBAttribute(attributeName = "value" )
    private BigDecimal value;

    @DynamoDBAttribute(attributeName = "createdAt")
    private Date createdAt;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "creditCard")
    private CreditCard creditCard;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "transactionStatus")
    private TransactionStatus transactionStatus;

    @DynamoDBAttribute(attributeName = "historic")
    private Set<String> historic;

    public TransactionItem() {
    }


    public TransactionItem(String uid, Long sid, String clientName, BigDecimal value, Date createdAt, CreditCard creditCard, TransactionStatus transactionStatus, Set<String> historic) {
        this.uid = uid;
        this.sid = sid;
        this.clientName = clientName;
        this.value = value;
        this.createdAt = createdAt;
        this.creditCard = creditCard;
        this.transactionStatus = transactionStatus;
        this.historic = historic;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public Long getSid() {
        return sid;
    }

    public void setSid(Long sid) {
        this.sid = sid;
    }

    public String getClientName() {
        return clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    public BigDecimal getValue() {
        return value;
    }

    public void setValue(BigDecimal value) {
        this.value = value;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public CreditCard getCreditCard() {
        return creditCard;
    }

    public void setCreditCard(CreditCard creditCard) {
        this.creditCard = creditCard;
    }

    public TransactionStatus getTransactionStatus() {
        return transactionStatus;
    }

    public void setTransactionStatus(TransactionStatus transactionStatus) {
        this.transactionStatus = transactionStatus;
    }

    public Set<String> getHistoric() {
        return historic;
    }

    public void setHistoric(Set<String> historic) {
        this.historic = historic;
    }

}
