package com.persistence.dynamo.item;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.model.CreditCard;
import com.model.Transaction;
import com.utils.DateFormatter;

import java.math.BigDecimal;
import java.util.Date;

@DynamoDBTable(tableName = "transaction")
public class TransactionItem {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String uid;

    @DynamoDBRangeKey(attributeName = "sid")
    private Integer sid;

    @DynamoDBAttribute(attributeName = "clientName")
    private String clientName;

    @DynamoDBAttribute(attributeName = "value" )
    private BigDecimal value;

    @DynamoDBAttribute(attributeName = "createdAt")
    private Date createdAt;

    @DynamoDBTypeConvertedEnum
    private CreditCard creditCard;

    public TransactionItem() {
    }


    public TransactionItem(String uid, Integer sid, String clientName, BigDecimal value, Date createdAt, CreditCard creditCard) {
        this.uid = uid;
        this.sid = sid;
        this.clientName = clientName;
        this.value = value;
        this.createdAt = createdAt;
        this.creditCard = creditCard;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public Integer getSid() {
        return sid;
    }

    public void setSid(Integer sid) {
        this.sid = sid;
    }

    public String getClientName() {
        return clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    public BigDecimal getValue() {
        return value;
    }

    public void setValue(BigDecimal value) {
        this.value = value;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public CreditCard getCreditCard() {
        return creditCard;
    }

    public void setCreditCard(CreditCard creditCard) {
        this.creditCard = creditCard;
    }
}
